## Continution to Previous Numpy Notebook 
(c) Dr. Naveen Aggarwal

### Matrix Operations on Arrays

In [1]:
import numpy as np

In [2]:
a=np.array([[2,3],[7,8]])
print(a)
b=np.eye(2)
print(b)

[[2 3]
 [7 8]]
[[1. 0.]
 [0. 1.]]


In [3]:
# transpose of matrix
print(a.transpose())

[[2 7]
 [3 8]]


In [4]:
# Inverse of matrix
from numpy.linalg import inv
print(inv(a))

[[-1.6  0.6]
 [ 1.4 -0.4]]


In [5]:
#product of two matrices
c=np.dot(a,b)
print(c)

[[2. 3.]
 [7. 8.]]


### Converting Array into matrices

In [6]:
a = np.array([[1,2],[3,4]]) 
m1 = np.mat(a) # convert 2-d array to matrix 
m = np.matrix([[1, 2], [3, 4]]) 
print(a)
print(m1)
print(m)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


### Difference between Operatons on Array and Matrices

In [7]:
# Normal Array result is 1-dimensional 
print(a[1])

[3 4]


In [9]:
# On Matrix, result is 2-dimensional 
print(m[1]) 

[[3 4]]


In [9]:
# element-by-element multiplication on Normal Array
print(a*a) 
# (algebraic) matrix multiplication on Matrix
print(m*m)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [10]:
# element-wise power on Array
print(a**3)
# matrix multiplication m*m*m 
print(m**3) 

[[ 1  8]
 [27 64]]
[[ 37  54]
 [ 81 118]]


In [10]:
# transpose of the matrix 
print(m.T) 
# conjugate transpose (differs from .T for complex matrices) 
print(m.H) 
# inverse matrix 
print(m.I) 

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


## Broadcasting Example

In [12]:
x = np.arange(4)
print("x =",x)
xx = x.reshape(4,1)
print("xx =",xx)
y = np.ones(5)
print("y =",y)
z = np.ones((3,4))
print("z =",z)

x = [0 1 2 3]
xx = [[0]
 [1]
 [2]
 [3]]
y = [1. 1. 1. 1. 1.]
z = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
print(x.shape, xx.shape, y.shape,z.shape)

(4,) (4, 1) (5,) (3, 4)


In [14]:
x+y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [25]:
xxy=xx+y
print(xxy)
print(xxy.shape)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
(4, 5)


In [15]:
xz=x+z
print(xz)
print(xz.shape)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
(3, 4)


## Vectorization

In [12]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0,6, 7, 8, 9, 0, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6,7, 8, 9]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0,7,8, 9, 4, 5, 6, 7, 8, 9,8, 5, 4, 5, 3, 8, 9, 5, 5]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(100000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(100000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000000*(toc - tic)) + "ms")

dot = 987
 ----- Computation time = 0.0ms
outer = [[81. 18. 18. ... 81. 45. 45.]
 [18.  4.  4. ... 18. 10. 10.]
 [45. 10. 10. ... 45. 25. 25.]
 ...
 [63. 14. 14. ... 63. 35. 35.]
 [72. 16. 16. ... 72. 40. 40.]
 [81. 18. 18. ... 81. 45. 45.]]
 ----- Computation time = 0.0ms
elementwise multiplication = [81.  4. 10.  0.  0. 63. 10.  0.  0.  0. 81.  4. 25.  0.  0. 42. 56. 72.
 36.  0. 18. 28. 40. 54. 56. 40. 36. 20. 15. 48. 63. 40. 45.]
 ----- Computation time = 0.0ms
gdot = [73.05415556 82.7166496  66.66990755]
 ----- Computation time = 0.0ms


In [13]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0,6, 7, 8, 9, 0, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6,7, 8, 9]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0,7,8, 9, 4, 5, 6, 7, 8, 9,8, 5, 4, 5, 3, 8, 9, 5, 5]
### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(10000*(toc - tic)) + "ms")

### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(10000*(toc - tic)) + "ms")

### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(10000*(toc - tic)) + "ms")

### VECTORIZED GENERAL DOT PRODUCT ###
tic = time.process_time()
dot = np.dot(W,x1)
toc = time.process_time()
print ("gdot = " + str(dot) + "\n ----- Computation time = " + str(10000*(toc - tic)) + "ms")

dot = 987
 ----- Computation time = 0.0ms
outer = [[81 18 18 ... 81 45 45]
 [18  4  4 ... 18 10 10]
 [45 10 10 ... 45 25 25]
 ...
 [63 14 14 ... 63 35 35]
 [72 16 16 ... 72 40 40]
 [81 18 18 ... 81 45 45]]
 ----- Computation time = 156.25ms
elementwise multiplication = [81  4 10  0  0 63 10  0  0  0 81  4 25  0  0 42 56 72 36  0 18 28 40 54
 56 40 36 20 15 48 63 40 45]
 ----- Computation time = 0.0ms
gdot = [73.05415556 82.7166496  66.66990755]
 ----- Computation time = 0.0ms


## 1 - Building basic functions with numpy ##

sigmoid function, np.exp() ###

Before using np.exp(), lets use math.exp() to implement the sigmoid function. You will then see why np.exp() is preferable to math.exp().


$sigmoid(x) = \frac{1}{1+e^{-x}}$ is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.

<img src="images/Sigmoid.png" style="width:500px;height:228px;">

To refer to a function belonging to a specific package you could call it using package_name.function(). Run the code below to see an example with math.exp().

In [12]:
import math
#import numpy as np
def basic_sigmoid(x):
    """
    Compute sigmoid of x.

    """
     
    s = 1/(1+math.exp(-x))
    #s1=1/(1+np.exp(-x))
    
    return s 

In [13]:
basic_sigmoid(3)

0.9525741268224334

In [14]:
### One reason why we use "numpy" instead of "math" in Deep Learning ###
x = [1, 2, 3]
basic_sigmoid(x) # you will see this give an error when you run it, because x is a vector.

TypeError: bad operand type for unary -: 'list'

In [20]:
y=[]
for ele in x:
    y.append(basic_sigmoid(ele))
print(y)

[0.7310585786300049, 0.8807970779778823, 0.9525741268224334]


In [16]:
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


In [18]:
def np_sigmoid(x):
    """
    Compute sigmoid of x.

    """
     
    s1=1/(1+np.exp(-x))
    
    return s1 

In [30]:
print(np_sigmoid(x))

[0.73105858 0.88079708 0.95257413]
